// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/block_worker.proto

package alluxio.grpc;

public interface GenerateUserSpaceReportResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alluxio.grpc.block.GenerateUserSpaceReportResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string user_space_report = 1;</code>
   */
  boolean hasUserSpaceReport();
  /**
   * <code>optional string user_space_report = 1;</code>
   */
  java.lang.String getUserSpaceReport();
  /**
   * <code>optional string user_space_report = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserSpaceReportBytes();
}
