// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/block_worker.proto

package alluxio.grpc;

public interface GenerateUserSpaceReportRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alluxio.grpc.block.GenerateUserSpaceReportRequest)
    com.google.protobuf.MessageOrBuilder {
}
