// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/file_system_master.proto

package alluxio.grpc;

/**
 * Protobuf type {@code alluxio.grpc.file.GetUserWeightsResponse}
 */
public  final class GetUserWeightsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:alluxio.grpc.file.GetUserWeightsResponse)
    GetUserWeightsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetUserWeightsResponse.newBuilder() to construct.
  private GetUserWeightsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetUserWeightsResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetUserWeightsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              userWeights_ = com.google.protobuf.MapField.newMapField(
                  UserWeightsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.Long, java.lang.Double>
            userWeights__ = input.readMessage(
                UserWeightsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            userWeights_.getMutableMap().put(
                userWeights__.getKey(), userWeights__.getValue());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return alluxio.grpc.FileSystemMasterProto.internal_static_alluxio_grpc_file_GetUserWeightsResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetUserWeights();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return alluxio.grpc.FileSystemMasterProto.internal_static_alluxio_grpc_file_GetUserWeightsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            alluxio.grpc.GetUserWeightsResponse.class, alluxio.grpc.GetUserWeightsResponse.Builder.class);
  }

  public static final int USERWEIGHTS_FIELD_NUMBER = 1;
  private static final class UserWeightsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Long, java.lang.Double> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Long, java.lang.Double>newDefaultInstance(
                alluxio.grpc.FileSystemMasterProto.internal_static_alluxio_grpc_file_GetUserWeightsResponse_UserWeightsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT64,
                0L,
                com.google.protobuf.WireFormat.FieldType.DOUBLE,
                0D);
  }
  private com.google.protobuf.MapField<
      java.lang.Long, java.lang.Double> userWeights_;
  private com.google.protobuf.MapField<java.lang.Long, java.lang.Double>
  internalGetUserWeights() {
    if (userWeights_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          UserWeightsDefaultEntryHolder.defaultEntry);
    }
    return userWeights_;
  }

  public int getUserWeightsCount() {
    return internalGetUserWeights().getMap().size();
  }
  /**
   * <code>map&lt;int64, double&gt; userWeights = 1;</code>
   */

  public boolean containsUserWeights(
      long key) {
    
    return internalGetUserWeights().getMap().containsKey(key);
  }
  /**
   * Use {@link #getUserWeightsMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.Long, java.lang.Double> getUserWeights() {
    return getUserWeightsMap();
  }
  /**
   * <code>map&lt;int64, double&gt; userWeights = 1;</code>
   */

  public java.util.Map<java.lang.Long, java.lang.Double> getUserWeightsMap() {
    return internalGetUserWeights().getMap();
  }
  /**
   * <code>map&lt;int64, double&gt; userWeights = 1;</code>
   */

  public double getUserWeightsOrDefault(
      long key,
      double defaultValue) {
    
    java.util.Map<java.lang.Long, java.lang.Double> map =
        internalGetUserWeights().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;int64, double&gt; userWeights = 1;</code>
   */

  public double getUserWeightsOrThrow(
      long key) {
    
    java.util.Map<java.lang.Long, java.lang.Double> map =
        internalGetUserWeights().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeLongMapTo(
        output,
        internalGetUserWeights(),
        UserWeightsDefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.Long, java.lang.Double> entry
         : internalGetUserWeights().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Long, java.lang.Double>
      userWeights__ = UserWeightsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, userWeights__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof alluxio.grpc.GetUserWeightsResponse)) {
      return super.equals(obj);
    }
    alluxio.grpc.GetUserWeightsResponse other = (alluxio.grpc.GetUserWeightsResponse) obj;

    boolean result = true;
    result = result && internalGetUserWeights().equals(
        other.internalGetUserWeights());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetUserWeights().getMap().isEmpty()) {
      hash = (37 * hash) + USERWEIGHTS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetUserWeights().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static alluxio.grpc.GetUserWeightsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static alluxio.grpc.GetUserWeightsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static alluxio.grpc.GetUserWeightsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static alluxio.grpc.GetUserWeightsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static alluxio.grpc.GetUserWeightsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static alluxio.grpc.GetUserWeightsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static alluxio.grpc.GetUserWeightsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static alluxio.grpc.GetUserWeightsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static alluxio.grpc.GetUserWeightsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static alluxio.grpc.GetUserWeightsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static alluxio.grpc.GetUserWeightsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static alluxio.grpc.GetUserWeightsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(alluxio.grpc.GetUserWeightsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code alluxio.grpc.file.GetUserWeightsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:alluxio.grpc.file.GetUserWeightsResponse)
      alluxio.grpc.GetUserWeightsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return alluxio.grpc.FileSystemMasterProto.internal_static_alluxio_grpc_file_GetUserWeightsResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetUserWeights();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableUserWeights();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return alluxio.grpc.FileSystemMasterProto.internal_static_alluxio_grpc_file_GetUserWeightsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              alluxio.grpc.GetUserWeightsResponse.class, alluxio.grpc.GetUserWeightsResponse.Builder.class);
    }

    // Construct using alluxio.grpc.GetUserWeightsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      internalGetMutableUserWeights().clear();
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return alluxio.grpc.FileSystemMasterProto.internal_static_alluxio_grpc_file_GetUserWeightsResponse_descriptor;
    }

    public alluxio.grpc.GetUserWeightsResponse getDefaultInstanceForType() {
      return alluxio.grpc.GetUserWeightsResponse.getDefaultInstance();
    }

    public alluxio.grpc.GetUserWeightsResponse build() {
      alluxio.grpc.GetUserWeightsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public alluxio.grpc.GetUserWeightsResponse buildPartial() {
      alluxio.grpc.GetUserWeightsResponse result = new alluxio.grpc.GetUserWeightsResponse(this);
      int from_bitField0_ = bitField0_;
      result.userWeights_ = internalGetUserWeights();
      result.userWeights_.makeImmutable();
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof alluxio.grpc.GetUserWeightsResponse) {
        return mergeFrom((alluxio.grpc.GetUserWeightsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(alluxio.grpc.GetUserWeightsResponse other) {
      if (other == alluxio.grpc.GetUserWeightsResponse.getDefaultInstance()) return this;
      internalGetMutableUserWeights().mergeFrom(
          other.internalGetUserWeights());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      alluxio.grpc.GetUserWeightsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (alluxio.grpc.GetUserWeightsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.Long, java.lang.Double> userWeights_;
    private com.google.protobuf.MapField<java.lang.Long, java.lang.Double>
    internalGetUserWeights() {
      if (userWeights_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            UserWeightsDefaultEntryHolder.defaultEntry);
      }
      return userWeights_;
    }
    private com.google.protobuf.MapField<java.lang.Long, java.lang.Double>
    internalGetMutableUserWeights() {
      onChanged();;
      if (userWeights_ == null) {
        userWeights_ = com.google.protobuf.MapField.newMapField(
            UserWeightsDefaultEntryHolder.defaultEntry);
      }
      if (!userWeights_.isMutable()) {
        userWeights_ = userWeights_.copy();
      }
      return userWeights_;
    }

    public int getUserWeightsCount() {
      return internalGetUserWeights().getMap().size();
    }
    /**
     * <code>map&lt;int64, double&gt; userWeights = 1;</code>
     */

    public boolean containsUserWeights(
        long key) {
      
      return internalGetUserWeights().getMap().containsKey(key);
    }
    /**
     * Use {@link #getUserWeightsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, java.lang.Double> getUserWeights() {
      return getUserWeightsMap();
    }
    /**
     * <code>map&lt;int64, double&gt; userWeights = 1;</code>
     */

    public java.util.Map<java.lang.Long, java.lang.Double> getUserWeightsMap() {
      return internalGetUserWeights().getMap();
    }
    /**
     * <code>map&lt;int64, double&gt; userWeights = 1;</code>
     */

    public double getUserWeightsOrDefault(
        long key,
        double defaultValue) {
      
      java.util.Map<java.lang.Long, java.lang.Double> map =
          internalGetUserWeights().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int64, double&gt; userWeights = 1;</code>
     */

    public double getUserWeightsOrThrow(
        long key) {
      
      java.util.Map<java.lang.Long, java.lang.Double> map =
          internalGetUserWeights().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearUserWeights() {
      internalGetMutableUserWeights().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;int64, double&gt; userWeights = 1;</code>
     */

    public Builder removeUserWeights(
        long key) {
      
      internalGetMutableUserWeights().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, java.lang.Double>
    getMutableUserWeights() {
      return internalGetMutableUserWeights().getMutableMap();
    }
    /**
     * <code>map&lt;int64, double&gt; userWeights = 1;</code>
     */
    public Builder putUserWeights(
        long key,
        double value) {
      
      
      internalGetMutableUserWeights().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;int64, double&gt; userWeights = 1;</code>
     */

    public Builder putAllUserWeights(
        java.util.Map<java.lang.Long, java.lang.Double> values) {
      internalGetMutableUserWeights().getMutableMap()
          .putAll(values);
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:alluxio.grpc.file.GetUserWeightsResponse)
  }

  // @@protoc_insertion_point(class_scope:alluxio.grpc.file.GetUserWeightsResponse)
  private static final alluxio.grpc.GetUserWeightsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new alluxio.grpc.GetUserWeightsResponse();
  }

  public static alluxio.grpc.GetUserWeightsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<GetUserWeightsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetUserWeightsResponse>() {
    public GetUserWeightsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetUserWeightsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetUserWeightsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetUserWeightsResponse> getParserForType() {
    return PARSER;
  }

  public alluxio.grpc.GetUserWeightsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

