// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/file_system_master.proto

package alluxio.grpc;

public interface GetUserWeightsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alluxio.grpc.file.GetUserWeightsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 workerId = 1;</code>
   */
  boolean hasWorkerId();
  /**
   * <code>optional int64 workerId = 1;</code>
   */
  long getWorkerId();
}
