// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/file_system_master.proto

package alluxio.grpc;

public interface GetUserWeightsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alluxio.grpc.file.GetUserWeightsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;int64, double&gt; userWeights = 1;</code>
   */
  int getUserWeightsCount();
  /**
   * <code>map&lt;int64, double&gt; userWeights = 1;</code>
   */
  boolean containsUserWeights(
      long key);
  /**
   * Use {@link #getUserWeightsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Long, java.lang.Double>
  getUserWeights();
  /**
   * <code>map&lt;int64, double&gt; userWeights = 1;</code>
   */
  java.util.Map<java.lang.Long, java.lang.Double>
  getUserWeightsMap();
  /**
   * <code>map&lt;int64, double&gt; userWeights = 1;</code>
   */

  double getUserWeightsOrDefault(
      long key,
      double defaultValue);
  /**
   * <code>map&lt;int64, double&gt; userWeights = 1;</code>
   */

  double getUserWeightsOrThrow(
      long key);
}
