// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/file_system_master.proto

package alluxio.grpc;

public interface GetWeightsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alluxio.grpc.file.GetWeightsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 userId = 1;</code>
   */
  boolean hasUserId();
  /**
   * <code>optional int64 userId = 1;</code>
   */
  long getUserId();
}
