// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/file_system_master.proto

package alluxio.grpc;

public interface GetWeightsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alluxio.grpc.file.GetWeightsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;int64, double&gt; weights = 1;</code>
   */
  int getWeightsCount();
  /**
   * <code>map&lt;int64, double&gt; weights = 1;</code>
   */
  boolean containsWeights(
      long key);
  /**
   * Use {@link #getWeightsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Long, java.lang.Double>
  getWeights();
  /**
   * <code>map&lt;int64, double&gt; weights = 1;</code>
   */
  java.util.Map<java.lang.Long, java.lang.Double>
  getWeightsMap();
  /**
   * <code>map&lt;int64, double&gt; weights = 1;</code>
   */

  double getWeightsOrDefault(
      long key,
      double defaultValue);
  /**
   * <code>map&lt;int64, double&gt; weights = 1;</code>
   */

  double getWeightsOrThrow(
      long key);
}
