// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/file_system_master.proto

package alluxio.grpc;

/**
 * Protobuf type {@code alluxio.grpc.file.GetWeightsResponse}
 */
public  final class GetWeightsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:alluxio.grpc.file.GetWeightsResponse)
    GetWeightsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetWeightsResponse.newBuilder() to construct.
  private GetWeightsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetWeightsResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetWeightsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              weights_ = com.google.protobuf.MapField.newMapField(
                  WeightsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.Long, java.lang.Double>
            weights__ = input.readMessage(
                WeightsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            weights_.getMutableMap().put(
                weights__.getKey(), weights__.getValue());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return alluxio.grpc.FileSystemMasterProto.internal_static_alluxio_grpc_file_GetWeightsResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetWeights();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return alluxio.grpc.FileSystemMasterProto.internal_static_alluxio_grpc_file_GetWeightsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            alluxio.grpc.GetWeightsResponse.class, alluxio.grpc.GetWeightsResponse.Builder.class);
  }

  public static final int WEIGHTS_FIELD_NUMBER = 1;
  private static final class WeightsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Long, java.lang.Double> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Long, java.lang.Double>newDefaultInstance(
                alluxio.grpc.FileSystemMasterProto.internal_static_alluxio_grpc_file_GetWeightsResponse_WeightsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT64,
                0L,
                com.google.protobuf.WireFormat.FieldType.DOUBLE,
                0D);
  }
  private com.google.protobuf.MapField<
      java.lang.Long, java.lang.Double> weights_;
  private com.google.protobuf.MapField<java.lang.Long, java.lang.Double>
  internalGetWeights() {
    if (weights_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          WeightsDefaultEntryHolder.defaultEntry);
    }
    return weights_;
  }

  public int getWeightsCount() {
    return internalGetWeights().getMap().size();
  }
  /**
   * <code>map&lt;int64, double&gt; weights = 1;</code>
   */

  public boolean containsWeights(
      long key) {
    
    return internalGetWeights().getMap().containsKey(key);
  }
  /**
   * Use {@link #getWeightsMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.Long, java.lang.Double> getWeights() {
    return getWeightsMap();
  }
  /**
   * <code>map&lt;int64, double&gt; weights = 1;</code>
   */

  public java.util.Map<java.lang.Long, java.lang.Double> getWeightsMap() {
    return internalGetWeights().getMap();
  }
  /**
   * <code>map&lt;int64, double&gt; weights = 1;</code>
   */

  public double getWeightsOrDefault(
      long key,
      double defaultValue) {
    
    java.util.Map<java.lang.Long, java.lang.Double> map =
        internalGetWeights().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;int64, double&gt; weights = 1;</code>
   */

  public double getWeightsOrThrow(
      long key) {
    
    java.util.Map<java.lang.Long, java.lang.Double> map =
        internalGetWeights().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeLongMapTo(
        output,
        internalGetWeights(),
        WeightsDefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.Long, java.lang.Double> entry
         : internalGetWeights().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Long, java.lang.Double>
      weights__ = WeightsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, weights__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof alluxio.grpc.GetWeightsResponse)) {
      return super.equals(obj);
    }
    alluxio.grpc.GetWeightsResponse other = (alluxio.grpc.GetWeightsResponse) obj;

    boolean result = true;
    result = result && internalGetWeights().equals(
        other.internalGetWeights());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetWeights().getMap().isEmpty()) {
      hash = (37 * hash) + WEIGHTS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetWeights().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static alluxio.grpc.GetWeightsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static alluxio.grpc.GetWeightsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static alluxio.grpc.GetWeightsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static alluxio.grpc.GetWeightsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static alluxio.grpc.GetWeightsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static alluxio.grpc.GetWeightsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static alluxio.grpc.GetWeightsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static alluxio.grpc.GetWeightsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static alluxio.grpc.GetWeightsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static alluxio.grpc.GetWeightsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static alluxio.grpc.GetWeightsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static alluxio.grpc.GetWeightsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(alluxio.grpc.GetWeightsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code alluxio.grpc.file.GetWeightsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:alluxio.grpc.file.GetWeightsResponse)
      alluxio.grpc.GetWeightsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return alluxio.grpc.FileSystemMasterProto.internal_static_alluxio_grpc_file_GetWeightsResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetWeights();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableWeights();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return alluxio.grpc.FileSystemMasterProto.internal_static_alluxio_grpc_file_GetWeightsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              alluxio.grpc.GetWeightsResponse.class, alluxio.grpc.GetWeightsResponse.Builder.class);
    }

    // Construct using alluxio.grpc.GetWeightsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      internalGetMutableWeights().clear();
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return alluxio.grpc.FileSystemMasterProto.internal_static_alluxio_grpc_file_GetWeightsResponse_descriptor;
    }

    public alluxio.grpc.GetWeightsResponse getDefaultInstanceForType() {
      return alluxio.grpc.GetWeightsResponse.getDefaultInstance();
    }

    public alluxio.grpc.GetWeightsResponse build() {
      alluxio.grpc.GetWeightsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public alluxio.grpc.GetWeightsResponse buildPartial() {
      alluxio.grpc.GetWeightsResponse result = new alluxio.grpc.GetWeightsResponse(this);
      int from_bitField0_ = bitField0_;
      result.weights_ = internalGetWeights();
      result.weights_.makeImmutable();
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof alluxio.grpc.GetWeightsResponse) {
        return mergeFrom((alluxio.grpc.GetWeightsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(alluxio.grpc.GetWeightsResponse other) {
      if (other == alluxio.grpc.GetWeightsResponse.getDefaultInstance()) return this;
      internalGetMutableWeights().mergeFrom(
          other.internalGetWeights());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      alluxio.grpc.GetWeightsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (alluxio.grpc.GetWeightsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.Long, java.lang.Double> weights_;
    private com.google.protobuf.MapField<java.lang.Long, java.lang.Double>
    internalGetWeights() {
      if (weights_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            WeightsDefaultEntryHolder.defaultEntry);
      }
      return weights_;
    }
    private com.google.protobuf.MapField<java.lang.Long, java.lang.Double>
    internalGetMutableWeights() {
      onChanged();;
      if (weights_ == null) {
        weights_ = com.google.protobuf.MapField.newMapField(
            WeightsDefaultEntryHolder.defaultEntry);
      }
      if (!weights_.isMutable()) {
        weights_ = weights_.copy();
      }
      return weights_;
    }

    public int getWeightsCount() {
      return internalGetWeights().getMap().size();
    }
    /**
     * <code>map&lt;int64, double&gt; weights = 1;</code>
     */

    public boolean containsWeights(
        long key) {
      
      return internalGetWeights().getMap().containsKey(key);
    }
    /**
     * Use {@link #getWeightsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, java.lang.Double> getWeights() {
      return getWeightsMap();
    }
    /**
     * <code>map&lt;int64, double&gt; weights = 1;</code>
     */

    public java.util.Map<java.lang.Long, java.lang.Double> getWeightsMap() {
      return internalGetWeights().getMap();
    }
    /**
     * <code>map&lt;int64, double&gt; weights = 1;</code>
     */

    public double getWeightsOrDefault(
        long key,
        double defaultValue) {
      
      java.util.Map<java.lang.Long, java.lang.Double> map =
          internalGetWeights().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int64, double&gt; weights = 1;</code>
     */

    public double getWeightsOrThrow(
        long key) {
      
      java.util.Map<java.lang.Long, java.lang.Double> map =
          internalGetWeights().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearWeights() {
      internalGetMutableWeights().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;int64, double&gt; weights = 1;</code>
     */

    public Builder removeWeights(
        long key) {
      
      internalGetMutableWeights().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, java.lang.Double>
    getMutableWeights() {
      return internalGetMutableWeights().getMutableMap();
    }
    /**
     * <code>map&lt;int64, double&gt; weights = 1;</code>
     */
    public Builder putWeights(
        long key,
        double value) {
      
      
      internalGetMutableWeights().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;int64, double&gt; weights = 1;</code>
     */

    public Builder putAllWeights(
        java.util.Map<java.lang.Long, java.lang.Double> values) {
      internalGetMutableWeights().getMutableMap()
          .putAll(values);
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:alluxio.grpc.file.GetWeightsResponse)
  }

  // @@protoc_insertion_point(class_scope:alluxio.grpc.file.GetWeightsResponse)
  private static final alluxio.grpc.GetWeightsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new alluxio.grpc.GetWeightsResponse();
  }

  public static alluxio.grpc.GetWeightsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<GetWeightsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetWeightsResponse>() {
    public GetWeightsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetWeightsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetWeightsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetWeightsResponse> getParserForType() {
    return PARSER;
  }

  public alluxio.grpc.GetWeightsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

