// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/file_system_master.proto

package alluxio.grpc;

public interface SetUserWeightsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alluxio.grpc.file.SetUserWeightsResponse)
    com.google.protobuf.MessageOrBuilder {
}
